export const PERMISSIONS = {
    CREATE_POST: "CREATE_POST",
    EDIT_OWN_POST: "EDIT_OWN_POST",
    DELETE_OWN_POST: "DELETE_OWN_POST",

    EDIT_ANY_POST: "EDIT_ANY_POST",
    DELETE_ANY_POST: "DELETE_ANY_POST",

    VIEW_POST: "VIEW_POST",
};